# Generated by Django 4.1.1 on 2022-09-09 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 20, 55, 51, 489514)),
        ),
    ]
