# Generated by Django 4.1.1 on 2022-09-09 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0002_chirp_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chirp',
            old_name='user',
            new_name='authuser',
        ),
        migrations.AlterField(
            model_name='chirp',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 22, 20, 36, 48447)),
        ),
    ]
