# Generated by Django 4.1.1 on 2022-09-10 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0003_rename_user_chirp_authuser_alter_chirp_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirp',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 7, 22, 11, 426610, tzinfo=datetime.timezone.utc)),
        ),
    ]
