# Generated by Django 4.1.1 on 2022-09-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.TextField()),
                ('short_url', models.TextField(max_length=100)),
            ],
        ),
    ]
