# Generated by Django 4.1 on 2022-10-05 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=20)),
                ('showWins', models.CharField(max_length=200)),
                ('ancestorInfo', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='RabbitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
