# Generated by Django 4.1 on 2022-10-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbitmodel',
            name='caption',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='residentback',
            name='ancestorInfo',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='residentback',
            name='parents',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='residentfront',
            name='caption',
            field=models.TextField(max_length=100),
        ),
    ]
