# Generated by Django 4.1 on 2022-10-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_rabbitmodel_caption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rabbitmodel',
            name='user',
        ),
    ]
