# Generated by Django 4.1 on 2022-10-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_rabbitmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbitmodel',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
