# Generated by Django 4.1 on 2022-08-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='groceryitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('complete_date', models.DateField(verbose_name='date completed')),
                ('completed', models.BooleanField(verbose_name='completed')),
            ],
        ),
    ]
