# Generated by Django 4.1 on 2022-09-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0002_alter_groceryitem_complete_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='item_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='groceryitem',
            name='complete_date',
        ),
        migrations.RemoveField(
            model_name='groceryitem',
            name='pub_date',
        ),
    ]
