# Generated by Django 4.1 on 2022-09-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0003_rename_item_text_groceryitem_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='undo',
            field=models.BooleanField(default=True),
        ),
    ]
