# Generated by Django 4.1 on 2022-09-06 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0004_groceryitem_undo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='undo',
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
