# Generated by Django 3.1.5 on 2022-09-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=200, verbose_name='long_url')),
                ('short_url', models.CharField(max_length=24, verbose_name='short_url')),
            ],
        ),
    ]
