# Generated by Django 3.1.5 on 2022-09-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='long_url',
            field=models.CharField(max_length=2048, verbose_name='long_url'),
        ),
    ]
