# Generated by Django 4.1 on 2022-09-06 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 22, 57, 18, 471062, tzinfo=datetime.timezone.utc)),
        ),
    ]
