# Generated by Django 4.1 on 2022-09-06 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortener', '0002_urls_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
