# Generated by Django 3.1.5 on 2022-10-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_nsfw',
        ),
        migrations.AddField(
            model_name='image',
            name='is_NSFW',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.CharField(choices=[('unselected', 'Unselected'), ('bust', 'Bust'), ('half-Body', 'Half-body'), ('full-Body', 'Full-body')], default='Unselected', max_length=15),
        ),
    ]
