# Generated by Django 4.1.2 on 2022-10-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={},
        ),
        migrations.RemoveField(
            model_name='log',
            name='auth_users',
        ),
        migrations.RemoveField(
            model_name='log',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='log',
            name='logrun_post',
        ),
    ]
