# Generated by Django 4.1.2 on 2022-10-14 18:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_log_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='Token',
        ),
    ]
