# Generated by Django 4.1.2 on 2022-10-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_new_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New_Post',
        ),
    ]
