# Generated by Django 4.1.2 on 2022-10-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscle',
            name='muscle',
            field=models.ManyToManyField(to='exercise.exercise'),
        ),
    ]
