# Generated by Django 4.1.2 on 2022-10-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_alter_muscle_muscle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscle',
            name='muscle',
            field=models.ManyToManyField(related_name='muscle', to='exercise.exercise'),
        ),
    ]
