# Generated by Django 4.1.2 on 2022-10-14 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_alter_muscle_muscle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muscle',
            old_name='muscle',
            new_name='exercise',
        ),
    ]
