# Generated by Django 4.1 on 2022-08-31 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='content',
            new_name='list',
        ),
    ]
