# Generated by Django 3.1.5 on 2022-09-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocerylist',
            old_name='grocery_text',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='GroceryItem',
        ),
    ]
