# Generated by Django 3.1.5 on 2022-09-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_auto_20220901_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='comp_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
