# Generated by Django 3.1.5 on 2022-09-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0003_auto_20220901_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='description',
            field=models.CharField(default='Add Description', max_length=200),
        ),
    ]
