# Generated by Django 4.1.1 on 2022-09-13 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def set_author(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Post = apps.get_model('post', 'Post')
    Post.objects.update(author=User.objects.first())

def revert_author(apps, schema_editor):
    Post = apps.get_model('post', 'Post')
    Post.objects.update(author=None)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, db_constraint =False, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
