# Generated by Django 4.1.1 on 2022-10-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_alter_recipe_recipelines'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pricefilter',
            field=models.CharField(choices=[('one', '$'), ('two', '$$'), ('three', '$$$')], default='two', max_length=5),
        ),
    ]
