# Generated by Django 4.1.1 on 2022-10-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_alter_recipe_pricefilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pricefilter',
            field=models.CharField(choices=[('one', '$'), ('two', '$$'), ('three', '$$$')], default='two', max_length=5),
        ),
    ]
