# Generated by Django 4.1.1 on 2022-10-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0008_recipe_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='upload/', width_field=100),
        ),
    ]
