# Generated by Django 4.1.1 on 2022-10-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0009_alter_recipe_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='uploads/%Y/%m/%d/', width_field=100),
        ),
    ]
