# Generated by Django 4.1.1 on 2022-10-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0011_alter_recipe_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
