# Generated by Django 4.1 on 2022-10-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0013_alter_recipe_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
