# Generated by Django 4.1 on 2022-09-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_urlshortener_long_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='long_url',
            field=models.CharField(max_length=300),
        ),
    ]
