# Generated by Django 4.1.1 on 2022-09-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longurl', models.CharField(max_length=2048, unique=True, verbose_name='long url')),
                ('shortcode', models.CharField(max_length=16, unique=True, verbose_name='shortcode')),
            ],
        ),
    ]
