# Generated by Django 4.1 on 2022-09-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_url', models.CharField(max_length=500)),
                ('accessed', models.IntegerField(default=0)),
            ],
        ),
    ]
