# Generated by Django 4.1 on 2022-09-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longurl', models.CharField(max_length=225)),
                ('shorturl', models.CharField(max_length=10)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
