# Generated by Django 4.1 on 2022-09-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='shortcode',
            field=models.CharField(default="<'{Ep*", max_length=10),
        ),
    ]
