# Generated by Django 4.1.2 on 2022-10-20 22:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0002_workingset_workout_delete_planner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingset',
            name='workout_day',
        ),
        migrations.AddField(
            model_name='workingset',
            name='day',
            field=models.DateField(default=datetime.datetime(2022, 10, 20, 17, 47, 5, 189373)),
        ),
        migrations.AddField(
            model_name='workingset',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workingset',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
