# Generated by Django 4.1 on 2022-08-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
