# Generated by Django 4.1 on 2022-09-13 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chirps',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='chirps',
            name='auth_users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Chirp_post', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
