# Generated by Django 4.0.3 on 2022-09-19 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_alter_chirps_options_chirps_auth_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chirps',
            name='auth_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chirp_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
