# Generated by Django 4.1 on 2022-10-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smite', '0002_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='getter_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
