# Generated by Django 4.1.2 on 2022-10-18 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='auth_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
