# Generated by Django 4.1.2 on 2022-10-18 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_log_auth_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={},
        ),
    ]
