# Generated by Django 4.1 on 2022-08-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=4096, verbose_name='item description')),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('completion_date', models.DateTimeField(verbose_name='completion date')),
                ('is_complete', models.BinaryField(verbose_name='complete')),
            ],
        ),
    ]
