# Generated by Django 4.1.2 on 2022-10-13 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_word', models.CharField(max_length=50)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('addFav', models.BooleanField(default=False, verbose_name='favList')),
            ],
        ),
    ]
