# Generated by Django 4.1 on 2022-08-31 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='GroceryItem',
        ),
    ]
